// ═══════════════════════════════════════════════════════════════════════════════════
// 🌐 سياق اللغة - Language Context
// ═══════════════════════════════════════════════════════════════════════════════════
// هذا السياق يوفر دعم تغيير اللغة عبر صفحات التطبيق
// This context provides language selection across the app
// ─────────────────────────────────────────────────────────────────────────────────────

import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    nav: {
      home: 'Home',
      findLawyer: 'Find a Lawyer',
      howItWorks: 'How it works',
      about: 'About Us',
      login: 'Login',
      signUp: 'Sign Up',
      createAccount: 'Create Account',
    },
    layout: {
      platform: 'LawLink Platform',
      mode: 'Mode',
      palette: 'Palette',
      language: 'Language',
      summary: 'Summary',
      liveStatus: 'Live status',
      offlineMode: 'Offline mode',
      live: 'Live',
      unavailable: 'Unavailable',
    },
    footer: {
      services: 'Services',
      company: 'Company',
      about: 'About',
      contact: 'Contact',
      help: 'Help',
      privacy: 'Privacy',
      copyright: '© 2026 LawLink Inc. All rights reserved',
    },
    auth: {
      login: {
        title: 'Welcome Back',
        subtitle: 'Select account type to continue to LawLink',
        email: 'Email Address',
        password: 'Password',
        remember: 'Remember me',
        forgotPassword: 'Forgot Password?',
        signInAsClient: 'Sign In as Client',
        signInAsLawyer: 'Sign In as Lawyer',
        createAccount: 'Create Account',
        noAccount: 'New to LawLink?',
        clientPortal: 'Client Portal',
        lawyerPortal: 'Lawyer Portal',
      },
      register: {
        title: 'Create Account',
        subtitle: 'Start your professional legal journey today',
        fullName: 'Full Name',
        email: 'Email Address',
        password: 'Password',
        createAccountButton: 'Register →',
        alreadyHaveAccount: 'Already have an account?',
        signIn: 'Sign In',
        clientPortal: 'Client Portal',
        lawyerPortal: 'Lawyer Portal',
        placeholderFullName: 'John Doe',
        placeholderEmail: 'name@example.com',
        placeholderPassword: 'Create a strong password',
      },
      forgotPassword: {
        title: 'Reset Password',
        subtitle: 'Enter your email to receive a reset link.',
        email: 'Email Address',
        sendLink: 'Send Link →',
        backToLogin: '← Back to Login',
        successMessage: 'A password reset link has been sent if the email exists.',
      },
      resetPassword: {
        title: 'New Password',
        subtitle: 'Choose a new password to secure your account.',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        updatePassword: 'Update Password →',
        passwordMismatch: 'Passwords do not match.',
        fillAll: 'Please fill in both password fields.',
      },
      emailVerification: {
        title: 'Verify your email',
        description: "We've sent a verification link to your email address. Please click the link to activate your account.",
        goToInbox: 'Go to Inbox',
        resendLink: 'Resend link',
        didntReceive: 'Didn\'t receive an email?',
        resentMessage: 'Verification link resent. Please check your email.',
      },
      registerClient: {
        brandTitle: 'Complete Your Profile',
        brandSubtitle: 'Help us provide you with the best legal services.',
        title: 'Client Information',
        subtitle: 'Please provide additional details to complete your registration',
        phone1: 'Phone Number 1 *',
        phone2: 'Phone Number 2 (Optional)',
        dateOfBirth: 'Date of Birth *',
        gender: 'Gender *',
        income: 'Monthly Income (EGP) *',
        password: 'Password *',
        confirmPassword: 'Confirm Password *',
        completeRegistration: 'Complete Registration →',
        backToRegistration: '← Back to Registration',
        male: 'Male',
        female: 'Female',
        other: 'Other',
        selectGender: 'Select Gender',
        placeholderPhone: '+20 123 456 7890',
        placeholderIncome: '5000',
      },
      registerLawyer: {
        brandTitle: 'Professional Details',
        brandSubtitle: 'Complete your legal professional profile.',
        title: 'Lawyer Information',
        subtitle: 'Please provide your professional details to complete registration',
        phone1: 'Phone Number 1 *',
        phone2: 'Phone Number 2 (Optional)',
        dateOfBirth: 'Date of Birth *',
        gender: 'Gender *',
        licenseNumber: 'License Number *',
        specializations: 'Specializations * (Select 1-5)',
        password: 'Password *',
        confirmPassword: 'Confirm Password *',
        completeRegistration: 'Complete Registration →',
        backToRegistration: '← Back to Registration',
        male: 'Male',
        female: 'Female',
        other: 'Other',
        selectGender: 'Select Gender',
        placeholderPhone: '+20 123 456 7890',
        placeholderLicense: '1234567890',
        placeholderSpecializationsHint: 'Hold Ctrl (Cmd on Mac) to select multiple specializations',
      },
    },
    route: {
      home: { title: 'LawLink', subtitle: 'Connecting lawyers and clients with confidence.' },
      about: { title: 'About LawLink', subtitle: 'A smarter legal platform designed for modern Egypt.' },
      contact: { title: 'Contact Us', subtitle: 'Reach out to our support team with any legal question.' },
      services: { title: 'Our Services', subtitle: 'Comprehensive legal services for business, family, and civil law.' },
      howItWorks: { title: 'How It Works', subtitle: 'Simple steps to get legal support and case tracking online.' },
      findLawyer: { title: 'Find a Lawyer', subtitle: 'Browse verified professionals across Egypt by specialty.' },
      lawyers: { title: 'Lawyers Directory', subtitle: 'Search, compare and choose the ideal legal partner.' },
      lawyerProfile: { title: 'Lawyer Profile', subtitle: 'View lawyer expertise, cases, and client feedback.' },
      clientDashboard: { title: 'Client Dashboard', subtitle: 'All your cases, billing and updates in one place.' },
      clientProfile: { title: 'Your Profile', subtitle: 'Update your details and keep your legal identity current.' },
      clientEditProfile: { title: 'Edit Client Profile', subtitle: 'Keep your profile ready for fast case submission.' },
      clientSubmitCase: { title: 'Submit a New Case', subtitle: 'Send your documents and case details with confidence.' },
      clientCases: { title: 'My Cases', subtitle: 'Track your legal matters from filing to resolution.' },
      clientCaseDetails: { title: 'Case Details', subtitle: 'Review your case status, documents and timeline.' },
      clientUploadDocuments: { title: 'Upload Case Documents', subtitle: 'Securely attach files for your active legal matter.' },
      clientMessages: { title: 'Client Messages', subtitle: 'Send secure messages to your lawyer and support team.' },
      clientAppointments: { title: 'Appointments', subtitle: 'Book and manage your consultation schedule.' },
      clientNotifications: { title: 'Notifications', subtitle: 'Stay updated with case alerts and client reminders.' },
      clientPayment: { title: 'Payments', subtitle: 'Review invoices, make payments and view receipts.' },
      lawyerDashboard: { title: 'Lawyer Dashboard', subtitle: 'Manage assigned cases, schedules and client communication.' },
      lawyerProfileDashboard: { title: 'My Lawyer Profile', subtitle: 'Update your expertise, availability and credentials.' },
      lawyerEditProfile: { title: 'Edit Lawyer Profile', subtitle: 'Keep your practice profile polished and up to date.' },
      lawyerCases: { title: 'Assigned Cases', subtitle: 'Track your active cases and upcoming deadlines.' },
      lawyerCaseDetails: { title: 'Lawyer Case Details', subtitle: 'Manage the case lifecycle and client updates.' },
      lawyerUpdateStatus: { title: 'Update Case Status', subtitle: 'Log progress and update the legal timeline.' },
      lawyerUploadDocuments: { title: 'Upload Documents', subtitle: 'Share evidence and legal files safely.' },
      lawyerMessages: { title: 'Lawyer Messages', subtitle: 'Communicate directly with clients and case teams.' },
      lawyerAppointments: { title: 'Lawyer Schedule', subtitle: 'Organize meetings and court dates efficiently.' },
      lawyerCalendar: { title: 'Availability Calendar', subtitle: 'Keep your schedule visible and under control.' },
      adminDashboard: { title: 'Admin Dashboard', subtitle: 'Monitor cases, users and system activity.' },
      adminManageUsers: { title: 'Manage Users', subtitle: 'Create, update and remove user accounts.' },
      adminCreateUser: { title: 'Create User', subtitle: 'Add a new member to the platform.' },
      adminEditUser: { title: 'Edit User', subtitle: 'Update user permissions and profile details.' },
      adminDeleteUser: { title: 'Delete User', subtitle: 'Remove a user when access is no longer required.' },
      adminManageLawyers: { title: 'Manage Lawyers', subtitle: 'Review lawyer registrations and status.' },
      adminApproveLawyers: { title: 'Approve Lawyers', subtitle: 'Verify lawyer credentials and activate profiles.' },
      adminManageClients: { title: 'Manage Clients', subtitle: 'Monitor client activity and account details.' },
      adminManageCases: { title: 'Manage Cases', subtitle: 'Review case workflows and outcomes.' },
      adminCaseMonitoring: { title: 'Case Monitoring', subtitle: 'Inspect case progress and system alerts.' },
      adminReports: { title: 'System Reports', subtitle: 'Generate analytics for performance and compliance.' },
      adminLogs: { title: 'System Logs', subtitle: 'Track audit events and security activity.' },
      caseAll: { title: 'All Cases', subtitle: 'Browse every case and manage legal workflows.' },
      caseCreate: { title: 'Create Case', subtitle: 'Start a new legal case with smart guidance.' },
      caseDetails: { title: 'Case Overview', subtitle: 'Review case documents, timelines, and notes.' },
      caseTimeline: { title: 'Case Timeline', subtitle: 'Follow every milestone and court date in one view.' },
      caseDocuments: { title: 'Case Documents', subtitle: 'Upload and manage evidence documents securely.' },
      caseStatusTracking: { title: 'Case Status', subtitle: 'Track status updates and important deadlines.' },
      messagesInbox: { title: 'Inbox', subtitle: 'View your message history and client conversations.' },
      chat: { title: 'Live Chat', subtitle: 'Secure attorney messages in real time.' },
      sendMessage: { title: 'Send a Message', subtitle: 'Share details with your lawyer instantly.' },
      notifications: { title: 'Notifications Center', subtitle: 'All case alerts, reminders and updates.' },
      settings: { title: 'Settings', subtitle: 'Configure your LawLink preferences and account.' },
      help: { title: 'Help Center', subtitle: 'Access support, FAQs and legal guidance.' },
      terms: { title: 'Terms & Privacy', subtitle: 'Review platform policies and legal terms.' },
      notFound: { title: 'Page Not Found', subtitle: 'The page you are looking for does not exist.' },
    },
    page: {
      home: {
        feature1Title: 'Search Top-Rated Lawyers',
        feature1Copy: 'Use filters by practice area, location, and rating to connect with trusted legal professionals.',
        feature1Cta: 'Find a Lawyer',
        feature2Title: 'Manage Cases with Confidence',
        feature2Copy: 'Track milestones, upload documents, and keep your practitioner aligned with one dashboard.',
        feature2Cta: 'View My Cases',
        whyTitle: 'Why LawLink?',
        benefitVerified: 'Verified Attorneys',
        benefitVerifiedCopy: 'Only vetted professionals with proven track records are featured.',
        benefitProtection: 'End-to-End Protection',
        benefitProtectionCopy: 'Secure document upload, messaging, and workflow transparency from start to finish.',
        benefitMonitoring: 'Smart Case Monitoring',
        benefitMonitoringCopy: 'Automated updates and milestones keep you ahead of deadlines.',
        testimonialsTitle: 'Testimonials',
        testimonial1: 'LawLink made it easy for me to find a corporate lawyer with rapid onboarding and great communication.',
        testimonial1Author: '– Sarah K., Startup Founder',
        testimonial2: 'I can review case documents and status updates from my phone. The security and clarity have been outstanding.',
        testimonial2Author: '– Ahmed T., Client',
      },
      about: {
        missionTitle: 'Our Mission',
        missionCopy: 'Deliver accessible, transparent, and efficient legal services through technology and verified expertise.',
        visionTitle: 'Our Vision',
        visionCopy: 'A future where anyone can secure legal support anytime, with confidence and control.',
        valuesTitle: 'Our Values',
        valuesList: ['Integrity', 'Excellence', 'Security', 'Support'],
        workTitle: 'How We Work',
        steps: [
          'Register and verify your profile.',
          'Use smart matching to identify ideal lawyers.',
          'Track case progress and communicate directly.',
          'Review results and provide feedback.',
        ],
      },
      contact: {
        officeTitle: 'Office Information',
        email: 'Email: support@lawlink.com',
        phone: 'Phone: +1 (555) 123-4567',
        address: 'Address: 254 Legal Ave, Suite 110, Cairo',
        hours: 'Business Hours: Mon-Fri 9AM - 6PM',
        formName: 'Full Name',
        formEmail: 'Email Address',
        formSubject: 'Subject',
        formMessage: 'Your message',
        formButton: 'Send Message',
        faqTitle: 'Frequently Asked Questions',
        faqCopy: 'Check our help center for quick answers on onboarding, billing and case workflow.',
      },
      services: {
        introTitle: 'Get Started Today',
        introCopy: 'Build your legal portfolio, track your cases, and communicate with professionals on one platform.',
        createAccount: 'Create Account',
        service1Title: 'Legal Matching',
        service1Copy: 'AI-powered lawyer matching for your case needs.',
        service2Title: 'Case Tracking',
        service2Copy: 'Follow progress, milestones, and deadlines at a glance.',
        service3Title: 'Secure Document Upload',
        service3Copy: 'Encrypted uploads for legal documents and contracts.',
        service4Title: 'Instant Messaging',
        service4Copy: 'Direct chat with your lawyer within the platform.',
        service5Title: 'Appointment Scheduling',
        service5Copy: 'Book consultations and court dates efficiently.',
        service6Title: 'Payment Management',
        service6Copy: 'Transparent billing, invoices, and payment history.',
      },
      howItWorks: {
        heading: 'How LawLink Works',
        description: 'LawLink simplifies legal onboarding, matching, and case tracking for clients, lawyers, and admins.',
        stepsTitle: 'Step-by-step',
        step1: 'Client submits case details.',
        step2: 'Lawyer accepts or bids on case.',
        step3: 'Real-time status tracking and messages.',
        benefitsTitle: 'Platform Benefits',
        benefitsCopy: 'Complete transparency, document upload, appointment scheduling, and secure payments make legal work simple.',
      },
      findLawyer: {
        heading: 'Find the Right Legal Expert',
        subheading: 'Browse our verified network of top-tier attorneys. Filter by specialty, location, and experience to secure the best representation.',
        filtersLabel: 'Filters',
        practiceArea: 'Practice Area',
        searchPlaceholder: 'Search by name, firm, or specialty...',
        resultsFoundOne: 'Result Found',
        resultsFoundMany: 'Results Found',
        noResults: 'No legal professionals found matching your criteria.',
        clearFilters: 'Clear all filters',
        categories: {
          all: 'All',
          corporate: 'Corporate',
          family: 'Family',
          criminal: 'Criminal',
          realEstate: 'Real Estate',
          intellectualProperty: 'Intellectual Property',
        },
      },
      lawyerProfile: {
        aboutTitle: 'About',
        ratingLabel: 'Rating',
        locationLabel: 'Location',
        casesClosedLabel: 'Cases Closed',
        hireButton: 'Hire this Lawyer',
      },
      lawyersList: {
        searchPlaceholder: 'Search by name or specialty',
        casesHandledPrefix: 'Cases handled',
        viewProfile: 'View Profile',
      },
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      findLawyer: 'ابحث عن محامي',
      howItWorks: 'كيف يعمل',
      about: 'من نحن',
      login: 'تسجيل الدخول',
      signUp: 'إنشاء حساب',
      createAccount: 'إنشاء حساب',
    },
    layout: {
      platform: 'منصة لولاينك',
      mode: 'النمط',
      palette: 'الألوان',
      language: 'اللغة',
      summary: 'ملخص',
      liveStatus: 'الحالة المباشرة',
      offlineMode: 'وضع عدم الاتصال',
      live: 'مباشر',
      unavailable: 'غير متاح',
    },
    footer: {
      services: 'الخدمات',
      company: 'الشركة',
      about: 'حول',
      contact: 'تواصل',
      help: 'المساعدة',
      privacy: 'الخصوصية',
      copyright: '© 2026 جميع الحقوق محفوظة لـ LawLink',
    },
    auth: {
      login: {
        title: 'مرحبا بعودتك',
        subtitle: 'اختر نوع الحساب للدخول إلى LawLink',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        remember: 'تذكّرني',
        forgotPassword: 'نسيت كلمة المرور؟',
        signInAsClient: 'الدخول كعميل',
        signInAsLawyer: 'الدخول كمحامي',
        createAccount: 'إنشاء حساب',
        noAccount: 'جديد على LawLink؟',
        clientPortal: 'بوابة العميل',
        lawyerPortal: 'بوابة المحامي',
      },
      register: {
        title: 'إنشاء حساب',
        subtitle: 'ابدأ رحلتك القانونية المهنية اليوم',
        fullName: 'الاسم الكامل',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        createAccountButton: 'سجل →',
        alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
        signIn: 'تسجيل الدخول',
        clientPortal: 'بوابة العميل',
        lawyerPortal: 'بوابة المحامي',
        placeholderFullName: 'أحمد علي',
        placeholderEmail: 'name@example.com',
        placeholderPassword: 'اكتب كلمة مرور قوية',
      },
      forgotPassword: {
        title: 'إعادة تعيين كلمة المرور',
        subtitle: 'أدخل بريدك الإلكتروني لتلقي رابط إعادة التعيين.',
        email: 'البريد الإلكتروني',
        sendLink: 'أرسل الرابط →',
        backToLogin: '← العودة لتسجيل الدخول',
        successMessage: 'تم إرسال رابط إعادة التعيين إذا كان البريد موجوداً.',
      },
      resetPassword: {
        title: 'كلمة المرور الجديدة',
        subtitle: 'اختر كلمة مرور جديدة لتأمين حسابك.',
        newPassword: 'كلمة المرور الجديدة',
        confirmPassword: 'تأكيد كلمة المرور',
        updatePassword: 'تحديث كلمة المرور →',
        passwordMismatch: 'كلمات المرور غير متطابقة.',
        fillAll: 'يرجى ملء حقلَي كلمة المرور.',
      },
      emailVerification: {
        title: 'تحقق من بريدك الإلكتروني',
        description: 'أرسلنا رابط التفعيل إلى بريدك الإلكتروني. يرجى الضغط على الرابط لتفعيل حسابك.',
        goToInbox: 'اذهب إلى البريد',
        resendLink: 'أعد إرسال الرابط',
        didntReceive: 'هل لم تستلم البريد؟',
        resentMessage: 'تم إعادة إرسال رابط التحقق. يرجى تفقد بريدك.',
      },
      registerClient: {
        brandTitle: 'أكمل ملفك',
        brandSubtitle: 'ساعدنا على تقديم أفضل الخدمات القانونية لك.',
        title: 'معلومات العميل',
        subtitle: 'أكمل بياناتك لإتمام التسجيل',
        phone1: 'رقم الهاتف 1 *',
        phone2: 'رقم الهاتف 2 (اختياري)',
        dateOfBirth: 'تاريخ الميلاد *',
        gender: 'الجنس *',
        income: 'الدخل الشهري (جنيه) *',
        password: 'كلمة المرور *',
        confirmPassword: 'تأكيد كلمة المرور *',
        completeRegistration: 'أكمل التسجيل →',
        backToRegistration: '← العودة للتسجيل',
        male: 'ذكر',
        female: 'أنثى',
        other: 'آخر',
        selectGender: 'اختر الجنس',
        placeholderPhone: '+20 123 456 7890',
        placeholderIncome: '5000',
      },
      registerLawyer: {
        brandTitle: 'تفاصيل الخبرة',
        brandSubtitle: 'أكمل ملفك المهني القانوني.',
        title: 'معلومات المحامي',
        subtitle: 'قدّم بياناتك المهنية لإكمال التسجيل',
        phone1: 'رقم الهاتف 1 *',
        phone2: 'رقم الهاتف 2 (اختياري)',
        dateOfBirth: 'تاريخ الميلاد *',
        gender: 'الجنس *',
        licenseNumber: 'رقم الترخيص *',
        specializations: 'التخصصات * (اختر 1-5)',
        password: 'كلمة المرور *',
        confirmPassword: 'تأكيد كلمة المرور *',
        completeRegistration: 'أكمل التسجيل →',
        backToRegistration: '← العودة للتسجيل',
        male: 'ذكر',
        female: 'أنثى',
        other: 'آخر',
        selectGender: 'اختر الجنس',
        placeholderPhone: '+20 123 456 7890',
        placeholderLicense: '1234567890',
        placeholderSpecializationsHint: 'اضغط Ctrl (أو Cmd على Mac) لاختيار أكثر من تخصص',
      },
    },
    route: {
      home: { title: 'لولاينك', subtitle: 'ربط المحامين والعملاء بثقة.' },
      about: { title: 'حول لولاينك', subtitle: 'منصة قانونية أذكى مصممة لمصر الحديثة.' },
      contact: { title: 'تواصل معنا', subtitle: 'تواصل مع فريق الدعم لأي سؤال قانوني.' },
      services: { title: 'خدماتنا', subtitle: 'خدمات قانونية شاملة للأعمال والأسرة والقضايا المدنية.' },
      howItWorks: { title: 'كيف يعمل', subtitle: 'خطوات بسيطة للحصول على الدعم القانوني وتتبع القضايا عبر الإنترنت.' },
      findLawyer: { title: 'ابحث عن محامي', subtitle: 'تصفح المتخصصين المعتمدين عبر مصر حسب التخصص.' },
      lawyers: { title: 'دليل المحامين', subtitle: 'ابحث وقارن واختر الشريك القانوني المثالي.' },
      lawyerProfile: { title: 'ملف المحامي', subtitle: 'اطلع على خبرات المحامي والقضايا وتعليقات العملاء.' },
      clientDashboard: { title: 'لوحة العميل', subtitle: 'كل قضاياك والفواتير والتحديثات في مكان واحد.' },
      clientProfile: { title: 'ملفك الشخصي', subtitle: 'حدّث بياناتك واحفظ هويتك القانونية محدثة.' },
      clientEditProfile: { title: 'تحرير ملف العميل', subtitle: 'حافظ على جاهزية ملفك لتقديم القضية بسرعة.' },
      clientSubmitCase: { title: 'قدّم قضية جديدة', subtitle: 'أرسل مستنداتك وتفاصيل القضية بثقة.' },
      clientCases: { title: 'قضاياى', subtitle: 'تابع شؤونك القانونية من التسجيل حتى الحل.' },
      clientCaseDetails: { title: 'تفاصيل القضية', subtitle: 'راجع حالة قضيتك والمستندات والزمنية.' },
      clientUploadDocuments: { title: 'رفع مستندات القضية', subtitle: 'أضف ملفات القضية بأمان.' },
      clientMessages: { title: 'رسائل العميل', subtitle: 'أرسل رسائل آمنة للمحامي وفريق الدعم.' },
      clientAppointments: { title: 'المواعيد', subtitle: 'احجز وأدِر جدول الاستشارات.' },
      clientNotifications: { title: 'الإشعارات', subtitle: 'تابع تنبيهات القضية والتذكيرات.' },
      clientPayment: { title: 'المدفوعات', subtitle: 'راجع الفواتير، ادفع، واطلع على الإيصالات.' },
      lawyerDashboard: { title: 'لوحة المحامي', subtitle: 'أدر القضايا المخصصة والنظام وجدولة العملاء.' },
      lawyerProfileDashboard: { title: 'ملف المحامي', subtitle: 'حدّث خبرتك وتوافراتك ومؤهلاتك.' },
      lawyerEditProfile: { title: 'تحرير ملف المحامي', subtitle: 'حافظ على احترافية ملفك الشخصي.' },
      lawyerCases: { title: 'القضايا المخصصة', subtitle: 'تابع قضاياك النشطة والمواعيد القادمة.' },
      lawyerCaseDetails: { title: 'تفاصيل قضية المحامي', subtitle: 'أدِر دورة حياة القضية وتحديثات العميل.' },
      lawyerUpdateStatus: { title: 'تحديث حالة القضية', subtitle: 'سجل التقدّم وحدّث الجدول القانوني.' },
      lawyerUploadDocuments: { title: 'رفع مستندات', subtitle: 'شارك الأدلة والملفات القانونية بأمان.' },
      lawyerMessages: { title: 'رسائل المحامي', subtitle: 'تواصل مباشرة مع العملاء وفريق القضية.' },
      lawyerAppointments: { title: 'جدول المحامي', subtitle: 'نظّم الاجتماعات ومواعيد المحاكم بكفاءة.' },
      lawyerCalendar: { title: 'التقويم', subtitle: 'اجعل جدولك مرئيًا وتحت السيطرة.' },
      adminDashboard: { title: 'لوحة الإدارة', subtitle: 'راقب القضايا والمستخدمين ونشاط النظام.' },
      adminManageUsers: { title: 'إدارة المستخدمين', subtitle: 'أنشئ، حدّث، واحذف الحسابات.' },
      adminCreateUser: { title: 'إنشاء مستخدم', subtitle: 'أضف عضوًا جديدًا للمنصة.' },
      adminEditUser: { title: 'تحرير مستخدم', subtitle: 'حدّث أذونات المستخدم وتفاصيل الملف.' },
      adminDeleteUser: { title: 'حذف مستخدم', subtitle: 'قم بإزالة مستخدم عند عدم الحاجة إلى الوصول.' },
      adminManageLawyers: { title: 'إدارة المحامين', subtitle: 'راجع تسجيلات المحامين وحالتهم.' },
      adminApproveLawyers: { title: 'الموافقة على المحامين', subtitle: 'تحقق من وثائق المحامين وفعل الملفات.' },
      adminManageClients: { title: 'إدارة العملاء', subtitle: 'راقب نشاط العملاء وتفاصيل الحساب.' },
      adminManageCases: { title: 'إدارة القضايا', subtitle: 'راجع سير القضايا والنتائج.' },
      adminCaseMonitoring: { title: 'مراقبة القضايا', subtitle: 'افحص تقدم القضايا وتنبيهات النظام.' },
      adminReports: { title: 'التقارير', subtitle: 'أنشئ تحليلات للأداء والامتثال.' },
      adminLogs: { title: 'سجلات النظام', subtitle: 'تتبع أحداث التدقيق والنشاط الأمني.' },
      caseAll: { title: 'كل القضايا', subtitle: 'تصفح جميع القضايا وأدر سير العمل القانوني.' },
      caseCreate: { title: 'إنشاء قضية', subtitle: 'ابدأ قضية قانونية جديدة مع إرشاد ذكي.' },
      caseDetails: { title: 'نظرة عامة على القضية', subtitle: 'راجع مستندات القضية والتواريخ والملاحظات.' },
      caseTimeline: { title: 'الجدول الزمني للقضية', subtitle: 'تابع كل مرحلة وكل موعد في عرض واحد.' },
      caseDocuments: { title: 'مستندات القضية', subtitle: 'ارفع وأدر ملفات الأدلة بأمان.' },
      caseStatusTracking: { title: 'حالة القضية', subtitle: 'تتبع تحديثات الحالة والمواعيد المهمة.' },
      messagesInbox: { title: 'صندوق الوارد', subtitle: 'عرض محفوظات الرسائل ومحادثات العملاء.' },
      chat: { title: 'الدردشة المباشرة', subtitle: 'رسائل آمنة للمحامي في الوقت الفعلي.' },
      sendMessage: { title: 'إرسال رسالة', subtitle: 'شارك التفاصيل مع محاميك فورًا.' },
      notifications: { title: 'مركز الإشعارات', subtitle: 'كل التنبيهات والتذكيرات والتحديثات.' },
      settings: { title: 'الإعدادات', subtitle: 'ضبط تفضيلات الحساب والمنصة.' },
      help: { title: 'مركز المساعدة', subtitle: 'الوصول إلى الدعم والأسئلة الشائعة والإرشادات.' },
      terms: { title: 'الشروط والخصوصية', subtitle: 'راجع سياسات المنصة والشروط القانونية.' },
      notFound: { title: 'الصفحة غير موجودة', subtitle: 'الصفحة التي تبحث عنها غير موجودة.' },
    },
    page: {
      home: {
        feature1Title: 'ابحث عن أفضل المحامين',
        feature1Copy: 'استخدم الفلاتر حسب التخصص والموقع والتقييم لتتواصل مع خبراء قانونيين موثوقين.',
        feature1Cta: 'ابحث عن محامي',
        feature2Title: 'أدر القضايا بثقة',
        feature2Copy: 'تابع المراحل وارفع المستندات واجعل المحامي الخاص بك متزامنًا عبر لوحة واحدة.',
        feature2Cta: 'عرض قضاياى',
        whyTitle: 'ليه LawLink؟',
        benefitVerified: 'محامين موثوقين',
        benefitVerifiedCopy: 'فقط المهنيين المعتمدين الذين لديهم سجل مثبت معروضين.',
        benefitProtection: 'حماية شاملة',
        benefitProtectionCopy: 'رفع مستندات آمن، ورسائل، وشفافية سير العمل من البداية للنهاية.',
        benefitMonitoring: 'متابعة القضايا الذكية',
        benefitMonitoringCopy: 'التحديثات التلقائية والمراحل تبقيك متقدمًا على المواعيد.',
        testimonialsTitle: 'آراء العملاء',
        testimonial1: 'LawLink سهل عليا أجيب محامي شركة بسرعة وتواصل ممتاز.',
        testimonial1Author: '– سارة ك., مؤسسة شركة',
        testimonial2: 'أقدر أراجع مستندات القضية وتحديث الحالة من الموبايل. الأمان والوضوح كانوا رائعين.',
        testimonial2Author: '– أحمد ت., عميل',
      },
      about: {
        missionTitle: 'مهمتنا',
        missionCopy: 'نوفر خدمات قانونية سهلة وشفافة وفعالة عبر التكنولوجيا والخبرة الموثوقة.',
        visionTitle: 'رؤيتنا',
        visionCopy: 'مستقبل يقدر أي حد يحصل على دعم قانوني في أي وقت بثقة وتحكم.',
        valuesTitle: 'قيمنا',
        valuesList: ['النزاهة', 'التميز', 'الأمان', 'الدعم'],
        workTitle: 'ازاي بنشتغل',
        steps: [
          'سجّل وتحقق من ملفك.',
          'استخدم المطابقة الذكية لتلاقي أفضل محامي.',
          'تابع تقدم القضية وتواصل مباشرة.',
          'راجع النتائج وقدم ملاحظات.',
        ],
      },
      contact: {
        officeTitle: 'معلومات المكتب',
        email: 'البريد الإلكتروني: support@lawlink.com',
        phone: 'الهاتف: +1 (555) 123-4567',
        address: 'العنوان: 254 Legal Ave, Suite 110, Cairo',
        hours: 'ساعات العمل: من الإثنين للجمعة 9ص - 6م',
        formName: 'الاسم بالكامل',
        formEmail: 'البريد الإلكتروني',
        formSubject: 'الموضوع',
        formMessage: 'رسالتك',
        formButton: 'إرسال رسالة',
        faqTitle: 'أسئلة شائعة',
        faqCopy: 'راجع مركز المساعدة لأسئلة سريعة عن التسجيل والفواتير وسير القضايا.',
      },
      services: {
        introTitle: 'ابدأ اليوم',
        introCopy: 'ابني ملفك القانوني، تابع القضايا، وتواصل مع المحترفين على منصة واحدة.',
        createAccount: 'إنشاء حساب',
        service1Title: 'مطابقة قانونية',
        service1Copy: 'مطابقة محامين مدفوعة بالذكاء الاصطناعي لاحتياجات قضيتك.',
        service2Title: 'متابعة القضايا',
        service2Copy: 'تابع التقدم والمراحل والمواعيد بكل وضوح.',
        service3Title: 'رفع مستندات آمن',
        service3Copy: 'رفع مشفر للمستندات القانونية والعقود.',
        service4Title: 'مراسلة فورية',
        service4Copy: 'دردشة مباشرة مع محاميك ضمن المنصة.',
        service5Title: 'حجز مواعيد',
        service5Copy: 'احجز الاستشارات ومواعيد المحكمة بكفاءة.',
        service6Title: 'إدارة الدفع',
        service6Copy: 'فواتير شفافة، إيصالات وتاريخ دفعات.',
      },
      howItWorks: {
        heading: 'إزاي شغال',
        description: 'LawLink يبسط التسجيل القانوني، المطابقة، وتتبع القضايا للعملاء والمحامين والإداريين.',
        stepsTitle: 'خطوات',
        step1: 'العميل يرسل تفاصيل القضية.',
        step2: 'المحامي يقبل أو يقدم عرض على القضية.',
        step3: 'تتبع الحالة في الوقت الحقيقي والرسائل.',
        benefitsTitle: 'مزايا المنصة',
        benefitsCopy: 'الشفافية الكاملة، رفع المستندات، حجز المواعيد، والدفع الآمن يخلي الشغل القانوني بسيط.',
      },
      findLawyer: {
        heading: 'دوّر على المحامي المناسب',
        subheading: 'تصفح شبكة المحامين المعتمدين. صفّي حسب التخصص، الموقع، والخبرة لتضمن التمثيل الأفضل.',
        filtersLabel: 'الفلاتر',
        practiceArea: 'مجال الممارسة',
        searchPlaceholder: 'ابحث بالاسم، المكتب، أو التخصص...',
        resultsFoundOne: 'نتيجة واحدة',
        resultsFoundMany: 'نتائج',
        noResults: 'مفيش محامين مطابقين للمعايير بتاعتك.',
        clearFilters: 'امسح كل الفلاتر',
        categories: {
          all: 'الكل',
          corporate: 'الشركات',
          family: 'الأسرة',
          criminal: 'الجنائي',
          realEstate: 'العقارات',
          intellectualProperty: 'الملكية الفكرية',
        },
      },
      lawyerProfile: {
        aboutTitle: 'حول',
        ratingLabel: 'التقييم',
        locationLabel: 'الموقع',
        casesClosedLabel: 'القضايا المنجزة',
        hireButton: 'وظّف هذا المحامي',
      },
      lawyersList: {
        searchPlaceholder: 'ابحث بالاسم أو التخصص',
        casesHandledPrefix: 'القضايا التي تعاملت معها',
        viewProfile: 'عرض الملف الشخصي',
      },
    },
  },
  eg: {
    nav: {
      home: 'الرئيسية',
      findLawyer: 'دوّر على محامي',
      howItWorks: 'إزاي شغال',
      about: 'عنّا',
      login: 'دخول',
      signUp: 'سجّل',
      createAccount: 'سجّل',
    },
    layout: {
      platform: 'منصة LawLink',
      mode: 'النمط',
      palette: 'ألوان',
      language: 'اللّغة',
      summary: 'ملخّص',
      liveStatus: 'الحالة المباشرة',
      offlineMode: 'أوفلاين',
      live: 'متاح',
      unavailable: 'مش متاح',
    },
    footer: {
      services: 'الخدمات',
      company: 'الشركة',
      about: 'عنّا',
      contact: 'تواصل',
      help: 'مساعدة',
      privacy: 'الخصوصية',
      copyright: '© 2026 حقوق LawLink محفوظة',
    },
    auth: {
      login: {
        title: 'أهلاً بيك تاني',
        subtitle: 'اختار نوع الحساب علشان تدخل على LawLink',
        email: 'البريد الإلكتروني',
        password: 'كلمة السر',
        remember: 'خلي الكمبيوتر يتذكّرني',
        forgotPassword: 'نسيت كلمة السر؟',
        signInAsClient: 'دخول كعميل',
        signInAsLawyer: 'دخول كمحامي',
        createAccount: 'سجل',
        noAccount: 'جديد على LawLink؟',
        clientPortal: 'بوابة العميل',
        lawyerPortal: 'بوابة المحامي',
      },
      register: {
        title: 'سجل حساب',
        subtitle: 'ابدأ رحلتك القانونية الاحترافية النهاردة',
        fullName: 'الاسم الكامل',
        email: 'البريد الإلكتروني',
        password: 'كلمة السر',
        createAccountButton: 'سجل →',
        alreadyHaveAccount: 'عندك حساب قبل كده؟',
        signIn: 'دخول',
        clientPortal: 'بوابة العميل',
        lawyerPortal: 'بوابة المحامي',
        placeholderFullName: 'أحمد علي',
        placeholderEmail: 'name@example.com',
        placeholderPassword: 'اكتب كلمة سر قوية',
      },
      forgotPassword: {
        title: 'استعادة كلمة السر',
        subtitle: 'اكتب بريدك الإلكتروني عشان يوصلك لينك جديد.',
        email: 'البريد الإلكتروني',
        sendLink: 'ابعت الرابط →',
        backToLogin: '← رجوع لتسجيل الدخول',
        successMessage: 'اللينك اتبعت لو البريد موجود.',
      },
      resetPassword: {
        title: 'كلمة السر الجديدة',
        subtitle: 'اختار كلمة سر جديدة علشان تأمن حسابك.',
        newPassword: 'كلمة السر الجديدة',
        confirmPassword: 'تأكيد كلمة السر',
        updatePassword: 'حدّث كلمة السر →',
        passwordMismatch: 'كلمات السر مش متطابقة.',
        fillAll: 'من فضلك عبّي الحقول الاتنين.',
      },
      emailVerification: {
        title: 'أكد بريدك الإلكتروني',
        description: 'بعتنا لك رابط التأكيد على بريدك. دوس على الرابط علشان تفعل حسابك.',
        goToInbox: 'روح للبريد',
        resendLink: 'ابعت اللينك تاني',
        didntReceive: 'ما وصلش بريد؟',
        resentMessage: 'لينك التحقق اتبعت تاني. شوف بريدك.',
      },
      registerClient: {
        brandTitle: 'كمّل ملفك',
        brandSubtitle: 'ساعدنا نقدملك أفضل خدمات قانونية.',
        title: 'بيانات العميل',
        subtitle: 'كمّل بياناتك علشان نخلص تسجيلك',
        phone1: 'رقم التليفون 1 *',
        phone2: 'رقم التليفون 2 (اختياري)',
        dateOfBirth: 'تاريخ الميلاد *',
        gender: 'الجنس *',
        income: 'الدخل الشهري (جنيه) *',
        password: 'كلمة السر *',
        confirmPassword: 'تأكيد كلمة السر *',
        completeRegistration: 'كمّل التسجيل →',
        backToRegistration: '← رجوع للتسجيل',
        male: 'راجل',
        female: 'ست',
        other: 'آخر',
        selectGender: 'اختار النوع',
        placeholderPhone: '+20 123 456 7890',
        placeholderIncome: '5000',
      },
      registerLawyer: {
        brandTitle: 'تفاصيلك المهنية',
        brandSubtitle: 'كمّل ملفك المهني القانوني.',
        title: 'بيانات المحامي',
        subtitle: 'أدخل بياناتك المهنية لتكمّل التسجيل',
        phone1: 'رقم التليفون 1 *',
        phone2: 'رقم التليفون 2 (اختياري)',
        dateOfBirth: 'تاريخ الميلاد *',
        gender: 'الجنس *',
        licenseNumber: 'رقم الترخيص *',
        specializations: 'التخصصات * (اختار 1-5)',
        password: 'كلمة السر *',
        confirmPassword: 'تأكيد كلمة السر *',
        completeRegistration: 'كمّل التسجيل →',
        backToRegistration: '← رجوع للتسجيل',
        male: 'راجل',
        female: 'ست',
        other: 'آخر',
        selectGender: 'اختار النوع',
        placeholderPhone: '+20 123 456 7890',
        placeholderLicense: '1234567890',
        placeholderSpecializationsHint: 'اضغط Ctrl (أو Cmd على Mac) عشان تختار أكتر من تخصص',
      },
    },
    route: {
      home: { title: 'LawLink', subtitle: 'يوصل بين العملاء والمحامين بثقة.' },
      about: { title: 'عن LawLink', subtitle: 'منصة قانونية ذكية مناسبة لمصر.' },
      contact: { title: 'كلمنا', subtitle: 'ابعت لفريق الدعم عن أي سؤال قانوني.' },
      services: { title: 'خدماتنا', subtitle: 'خدمات قانونية للأعمال والأسرة والقضايا المدنية.' },
      howItWorks: { title: 'إزاي شغال', subtitle: 'خطوات بسيطة للدعم القانوني وتتبع القضايا أونلاين.' },
      findLawyer: { title: 'دوّر على محامي', subtitle: 'تصفح المحامين المعتمدين في مصر حسب التخصص.' },
      lawyers: { title: 'دليل المحامين', subtitle: 'قارن واختار الشريك القانوني المناسب.' },
      lawyerProfile: { title: 'صفحة المحامي', subtitle: 'شوف خبرته، قضاياه، وردود العملاء.' },
      clientDashboard: { title: 'لوحة العميل', subtitle: 'كل قضاياك والفواتير والتحديثات مكان واحد.' },
      clientProfile: { title: 'الملف بتاعك', subtitle: 'حدّث بياناتك وخلي ملفك دايمًا جاهز.' },
      clientEditProfile: { title: 'تعديل ملف العميل', subtitle: 'خلي ملفك مستعد بسرعة لتقديم القضية.' },
      clientSubmitCase: { title: 'قدّم قضية', subtitle: 'بعت مستنداتك وتفاصيل قضيتك بثقة.' },
      clientCases: { title: 'قضايا', subtitle: 'تابع القضايا من البداية للنهاية.' },
      clientCaseDetails: { title: 'تفاصيل القضية', subtitle: 'راجع حالة القضية والمستندات والتوقيت.' },
      clientUploadDocuments: { title: 'رفع ملفات القضية', subtitle: 'ضيف ملفات القضية بأمان.' },
      clientMessages: { title: 'رسائل العميل', subtitle: 'ابعت رسائل آمنة للمحامي وفريق الدعم.' },
      clientAppointments: { title: 'المواعيد', subtitle: 'احجز ونظم مواعيد الاستشارة.' },
      clientNotifications: { title: 'الإشعارات', subtitle: 'تابع تنبيهات القضايا والتذكيرات.' },
      clientPayment: { title: 'الدفع', subtitle: 'راجع الفواتير واستلم الإيصالات.' },
      lawyerDashboard: { title: 'لوحة المحامي', subtitle: 'نظم القضايا، المواعيد، والتواصل.' },
      lawyerProfileDashboard: { title: 'ملف المحامي', subtitle: 'حدّث خبرتك وتوافراتك.' },
      lawyerEditProfile: { title: 'تعديل ملف المحامي', subtitle: 'خلي ملفك محترف ومحدّث.' },
      lawyerCases: { title: 'القضايا المخصصة', subtitle: 'تابع القضايا والنهايات القادمة.' },
      lawyerCaseDetails: { title: 'تفاصيل القضية', subtitle: 'نظم حالة القضية وتحديثات العميل.' },
      lawyerUpdateStatus: { title: 'تحديث الحالة', subtitle: 'سجل التقدم وحدث الجدول.' },
      lawyerUploadDocuments: { title: 'رفع ملفات', subtitle: 'بعت الأدلة والورق بأمان.' },
      lawyerMessages: { title: 'رسائل المحامي', subtitle: 'كلم العملاء وفريق القضية.' },
      lawyerAppointments: { title: 'جدول المحامي', subtitle: 'نظم مواعيدك ومواعيد المحكمة.' },
      lawyerCalendar: { title: 'التقويم', subtitle: 'خلّي جدولك واضح وتحت السيطرة.' },
      adminDashboard: { title: 'لوحة الإدارة', subtitle: 'راقب القضايا والمستخدمين والنظام.' },
      adminManageUsers: { title: 'إدارة المستخدمين', subtitle: 'أضف وعدل واحذف الحسابات.' },
      adminCreateUser: { title: 'إنشاء مستخدم', subtitle: 'ضيف عضو جديد للمنصة.' },
      adminEditUser: { title: 'تعديل مستخدم', subtitle: 'حدث صلاحيات وبيانات المستخدم.' },
      adminDeleteUser: { title: 'حذف مستخدم', subtitle: 'امسح مستخدم لو مش محتاج دخوله.' },
      adminManageLawyers: { title: 'إدارة المحامين', subtitle: 'راجع تسجيلات المحامين وحالتهم.' },
      adminApproveLawyers: { title: 'الموافقة على المحامين', subtitle: 'تحقق من بيانات المحامين وفعلهم.' },
      adminManageClients: { title: 'إدارة العملاء', subtitle: 'راقب نشاط العملاء وحساباتهم.' },
      adminManageCases: { title: 'إدارة القضايا', subtitle: 'راجع سير القضايا والنتايج.' },
      adminCaseMonitoring: { title: 'مراقبة القضايا', subtitle: 'اشوف تقدم القضايا وتنبيهات النظام.' },
      adminReports: { title: 'التقارير', subtitle: 'اطلع على تحليلات الأداء والالتزام.' },
      adminLogs: { title: 'سجلات النظام', subtitle: 'تابع أحداث الأمان والتدقيق.' },
      caseAll: { title: 'كل القضايا', subtitle: 'تصفح القضايا وأدر سير العمل.' },
      caseCreate: { title: 'إنشاء قضية', subtitle: 'ابدأ قضية جديدة مع إرشاد.' },
      caseDetails: { title: 'نظرة عامة على القضية', subtitle: 'راجع مستندات القضية والمواعيد.' },
      caseTimeline: { title: 'الجدول الزمني', subtitle: 'تابع كل مرحلة وموعد.' },
      caseDocuments: { title: 'ملفات القضية', subtitle: 'ارفع وأدر ملفات الأدلة.' },
      caseStatusTracking: { title: 'حالة القضية', subtitle: 'تابع التحديثات والمواعيد.' },
      messagesInbox: { title: 'صندوق الرسائل', subtitle: 'راجع محادثات العملاء.' },
      chat: { title: 'الدردشة', subtitle: 'راسل المحامي مباشرة.' },
      sendMessage: { title: 'إرسال رسالة', subtitle: 'ابعت التفاصيل بسرعة.' },
      notifications: { title: 'الإشعارات', subtitle: 'كل التنبيهات والتذكيرات.' },
      settings: { title: 'الإعدادات', subtitle: 'ضبط تفضيلات الحساب.' },
      help: { title: 'المساعدة', subtitle: 'الوصول للدعم والأسئلة.' },
      terms: { title: 'الشروط والخصوصية', subtitle: 'راجع السياسات والشروط.' },
      notFound: { title: 'الصفحة مش لاقيها', subtitle: 'الصفحة اللي بتدور عليها مش موجودة.' },
    },
    page: {
      home: {
        feature1Title: 'ابحث عن أفضل المحامين',
        feature1Copy: 'استخدم الفلاتر حسب التخصص والموقع والتقييم لتتواصل مع خبراء قانونيين موثوقين.',
        feature1Cta: 'ابحث عن محامي',
        feature2Title: 'أدر القضايا بثقة',
        feature2Copy: 'تابع المراحل وارفع المستندات وخلي المحامي بتاعك متزامن معك.',
        feature2Cta: 'اعرض قضايا',
        whyTitle: 'ليه LawLink؟',
        benefitVerified: 'محامين موثوقين',
        benefitVerifiedCopy: 'فقط المهنيين اللي اتوثقوا و ليهم سجل مثبت متوفرين.',
        benefitProtection: 'حماية شاملة',
        benefitProtectionCopy: 'رفع ملفات آمن، ورسائل، وشفافية سير العمل من البداية للنهاية.',
        benefitMonitoring: 'متابعة ذكية للقضايا',
        benefitMonitoringCopy: 'التحديثات التلقائية والمراحل تبقيك متقدم على المواعيد.',
        testimonialsTitle: 'شهادات العملاء',
        testimonial1: 'LawLink خلى عليا ألاقي محامي شركة بسرعة وتواصل ممتاز.',
        testimonial1Author: '– سارة ك., مؤسسة شركة',
        testimonial2: 'براجع مستندات القضية وتحديثات الحالة من الموبايل. الأمان والوضوح كانوا ممتازين.',
        testimonial2Author: '– أحمد ت., عميل',
      },
      about: {
        missionTitle: 'مهمتنا',
        missionCopy: 'نوفر خدمات قانونية سهلة وشفافة وفعالة بالتكنولوجيا والخبرة الموثوقة.',
        visionTitle: 'رؤيتنا',
        visionCopy: 'مستقبل يقدر أي حد يحصل فيه على دعم قانوني في أي وقت بثقة وتحكم.',
        valuesTitle: 'قيمنا',
        valuesList: ['النزاهة', 'التميز', 'الأمان', 'الدعم'],
        workTitle: 'ازاي بنشتغل',
        steps: [
          'سجل وتأكد من ملفك.',
          'استخدم المطابقة الذكية لتلاقي المحامي المناسب.',
          'تابع تقدم القضية وتواصل مباشرة.',
          'راجع النتائج وقدم رأيك.',
        ],
      },
      contact: {
        officeTitle: 'معلومات المكتب',
        email: 'البريد الإلكتروني: support@lawlink.com',
        phone: 'التليفون: +1 (555) 123-4567',
        address: 'العنوان: 254 Legal Ave, Suite 110, Cairo',
        hours: 'ساعات العمل: من الاتنين للجمعة 9ص - 6م',
        formName: 'الاسم بالكامل',
        formEmail: 'البريد الإلكتروني',
        formSubject: 'الموضوع',
        formMessage: 'رسالتك',
        formButton: 'ابعت رسالة',
        faqTitle: 'أسئلة متكررة',
        faqCopy: 'شوف مركز المساعدة لأسئلة سريعة عن التسجيل والفواتير وسير القضية.',
      },
      services: {
        introTitle: 'ابدأ النهاردة',
        introCopy: 'ابني ملفك القانوني، تابع قضاياك، وكلم المحترفين على منصة واحدة.',
        createAccount: 'سجل',
        service1Title: 'مطابقة قانونية',
        service1Copy: 'مطابقة محامين بالذكاء الاصطناعي لاحتياجات قضيتك.',
        service2Title: 'متابعة القضايا',
        service2Copy: 'تابع التقدم والمراحل والمواعيد بكل وضوح.',
        service3Title: 'رفع مستندات آمن',
        service3Copy: 'رفع مشفر للمستندات القانونية والعقود.',
        service4Title: 'مراسلة فورية',
        service4Copy: 'دردشة مباشرة مع محاميك داخل المنصة.',
        service5Title: 'حجز مواعيد',
        service5Copy: 'احجز الاستشارات ومواعيد المحكمة بسهولة.',
        service6Title: 'إدارة الدفع',
        service6Copy: 'فواتير شفافة، إيصالات وسجل دفعات.',
      },
      howItWorks: {
        heading: 'إزاي شغال',
        description: 'LawLink يبسط التسجيل القانوني، المطابقة، وتتبع القضايا للعملاء والمحامين والإداريين.',
        stepsTitle: 'خطوات',
        step1: 'العميل يبعث تفاصيل القضية.',
        step2: 'المحامي يقبل أو يقدم عرض على القضية.',
        step3: 'تتبع الحالة والرسائل في الوقت الحقيقي.',
        benefitsTitle: 'مميزات المنصة',
        benefitsCopy: 'الشفافية، رفع الملفات، حجز المواعيد والدفع الآمن يخلي الشغل القانوني أسهل.',
      },
      findLawyer: {
        heading: 'دوّر على المحامي المناسب',
        subheading: 'تصفح شبكة المحامين المعتمدين. صفّي حسب التخصص، المكان، والخبرة عشان تضمن التمثيل الأفضل.',
        filtersLabel: 'الفلاتر',
        practiceArea: 'مجال الممارسة',
        searchPlaceholder: 'ابحث بالاسم، المكتب، أو التخصص...',
        resultsFoundOne: 'نتيجة واحدة',
        resultsFoundMany: 'نتائج',
        noResults: 'مافيش محامين مطابقين للمعايير بتاعتك.',
        clearFilters: 'امسح كل الفلاتر',
        categories: {
          all: 'الكل',
          corporate: 'الشركات',
          family: 'الأسرة',
          criminal: 'الجنائي',
          realEstate: 'العقارات',
          intellectualProperty: 'الملكية الفكرية',
        },
      },
      lawyerProfile: {
        aboutTitle: 'حول',
        ratingLabel: 'التقييم',
        locationLabel: 'الموقع',
        casesClosedLabel: 'القضايا المنجزة',
        hireButton: 'وظّف المحامي دا',
      },
      lawyersList: {
        searchPlaceholder: 'ابحث بالاسم أو التخصص',
        casesHandledPrefix: 'القضايا اللي تعامل معاها',
        viewProfile: 'شوف الملف الشخصي',
      },
    },
  },
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  languages: [],
  t: (key, fallback) => fallback || key,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('lawlink-language') || 'en');

  useEffect(() => {
    localStorage.setItem('lawlink-language', language);
  }, [language]);

  const languages = useMemo(
    () => [
      { code: 'en', label: 'English' },
      { code: 'ar', label: 'العربية' },
      { code: 'eg', label: 'مصرى' },
    ],
    [],
  );

  const t = useMemo(
    () => (key, fallback = '') => {
      const keys = key.split('.');
      let current = translations[language] ?? translations.en;
      for (const part of keys) {
        current = current?.[part];
        if (current === undefined) {
          return fallback || key;
        }
      }
      return typeof current === 'string' ? current : fallback || key;
    },
    [language],
  );

  const value = useMemo(
    () => ({ language, setLanguage, languages, t }),
    [language, languages, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
export const Languagecontext = () => useContext(LanguageContext);
