const mongoose = require('mongoose');

const ConsultationSchema = new mongoose.Schema({
  clientId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  messages: [
    {
      sender: { type: String, enum: ['user', 'ai'], required: true },
      text: { type: String, required: true },
      timestamp: { type: Date, default: Date.now }
    }
  ],
  category: { type: String }, // e.g., "Family Law", "Labor Law"
  aiSummary: { type: String }, // Brief summary generated by AI
  status: { type: String, enum: ['active', 'archived'], default: 'active' }
});

module.exports = mongoose.model('Consultation', ConsultationSchema);
